### ISSUE TITLE
Getting the password hash

### ISSUE THREAD

**Issue by TraGicCode** [jorritfolmer/puppet-splunk#10]
What approach do you currently take to get the hashed password of users that you put in the passwd configuration file?

**Comment by stmyers** [comment]
I use `grub-crypt` (on cent/rhel)
`> /sbin/grub-crypt --sha-512
Password:
Retype password:
$6$Bo1Q7XwkT8rg5Jwf$t/NQRDx.4pUuI1jl4jz6bj.Ud28PZB0SNI43ZCcubdJOw/HOqRttKMSg7QKoR9q279/K7omrSuU5RU83.kuA30`

then you'll be prompted to enter the password twice and be output the hash.

**Comment by jorritfolmer** [comment]
Thanks! I've updated the README with instructions to generate SHA512 password hashes.
