### ISSUE TITLE
typo and missing parameter

### ISSUE THREAD

**Issue by negast** [jorritfolmer/puppet-splunk#11]
in the init.pp you have a typo on line 37
  $ds_intermediate            = $splunk::params::ds_intemediate,
should be 
  $ds_intermediate            = $splunk::params::ds_intermediate,

following parameter is missing in params.pp causing errors
splunk::params::ecdhcurvename_intermediate

variable in certs/s2s.pp is not declared line 7
 $use_certs     = $splunk::use_certs,

**Comment by jorritfolmer** [comment]
Thank you for sharing these!
I've fixed them in the most recent commit.
If you hit any other issues, please let me know.
