### ISSUE TITLE
splunk-launch.conf splunk_os_user: Could not evaluate: Saving failed

### ISSUE THREAD

**Issue by FlorinTar** [jorritfolmer/puppet-splunk#13]
Hi, 
I'm getting the below errors with puppet code:

  class { 'splunk':
    httpport           => 8000,
    kvstoreport        => 8191,
    inputport          => 9997,
    reuse_puppet_certs => false,
    sslcertpath        => 'server.pem',
    sslrootcapath      => 'cacert.pem',
  }

Any idea why ? Splunk version is 6.6.1. 

Below are the errors I'm seeing.

Debug: Augeas[/opt/splunk/etc/splunk-launch.conf splunk_os_user](provider=augeas): Opening augeas with root /, lens path , flags 64
Debug: Augeas[/opt/splunk/etc/splunk-launch.conf splunk_os_user](provider=augeas): Augeas version 1.4.0 is installed
Debug: Augeas[/opt/splunk/etc/splunk-launch.conf splunk_os_user](provider=augeas): Will attempt to save and only run if files changed
Debug: Augeas[/opt/splunk/etc/splunk-launch.conf splunk_os_user](provider=augeas): sending command 'set' with params ["/files/opt/splunk/etc/splunk-launch.conf/SPLUNK_OS_USER", "splunk"]
Debug: Augeas[/opt/splunk/etc/splunk-launch.conf splunk_os_user](provider=augeas): Closed the augeas connection
**Error: /Stage[main]/Splunk::Splunk_launch/Augeas[/opt/splunk/etc/splunk-launch.conf splunk_os_user]: Could not evaluate: Saving failed, see debug**
Debug: Augeas[/opt/splunk/etc/splunk-launch.conf splunk_bindip](provider=augeas): Opening augeas with root /, lens path , flags 64
Debug: Augeas[/opt/splunk/etc/splunk-launch.conf splunk_bindip](provider=augeas): Augeas version 1.4.0 is installed
Debug: Augeas[/opt/splunk/etc/splunk-launch.conf splunk_bindip](provider=augeas): Will attempt to save and only run if files changed
Debug: Augeas[/opt/splunk/etc/splunk-launch.conf splunk_bindip](provider=augeas): sending command 'rm' with params ["/files/opt/splunk/etc/splunk-launch.conf/SPLUNK_BINDIP"]
Debug: Augeas[/opt/splunk/etc/splunk-launch.conf splunk_bindip](provider=augeas): Skipping because no files were changed
Debug: Augeas[/opt/splunk/etc/splunk-launch.conf splunk_bindip](provider=augeas): Closed the augeas connection
Debug: Class[Splunk::Splunk_launch]: Resource is being skipped, unscheduling all events
Debug: Class[Splunk::Deploymentclient]: Resource is being skipped, unscheduling all events
**Notice: /Stage[main]/Splunk::Deploymentclient/File[/opt/splunk/etc/apps/puppet_common_deploymentclient_base]: Dependency Augeas[/opt/splunk/etc/splunk-launch.conf splunk_os_user] has failures: true
Warning: /Stage[main]/Splunk::Deploymentclient/File[/opt/splunk/etc/apps/puppet_common_deploymentclient_base]: Skipping because of failed dependencies**
Debug: /Stage[main]/Splunk::Deploymentclient/File[/opt/splunk/etc/apps/puppet_common_deploymentclient_base]: Resource is being skipped, unscheduling all events
Debug: Class[Splunk::Deploymentclient]: Resource is being skipped, unscheduling all events
Debug: Class[Splunk::Distsearch]: Resource is being skipped, unscheduling all events
Debug: Class[Splunk::Distsearch]: Resource is being skipped, unscheduling all events
Debug: Class[Splunk::Passwd]: Resource is being skipped, unscheduling all events
Debug: Class[Splunk::Passwd]: Resource is being skipped, unscheduling all events
Debug: Class[Splunk::Authentication]: Resource is being skipped, unscheduling all events
Debug: Class[Splunk::Authentication]: Resource is being skipped, unscheduling all events
Debug: Class[Splunk::Service]: Resource is being skipped, unscheduling all events
**Notice: /Stage[main]/Splunk::Service/Service[splunk]: Dependency Augeas[/opt/splunk/etc/splunk-launch.conf splunk_os_user] has failures: true
Warning: /Stage[main]/Splunk::Service/Service[splunk]: Skipping because of failed dependencies**
Debug: /Stage[main]/Splunk::Service/Service[splunk]: Resource is being skipped, unscheduling all events

**Comment by jorritfolmer** [comment]
I'm not able to reproduce this with Splunk 6.6.1 on:
- RHEL 7.1 and Puppet 3.7.x
- RHEL 7.3 and Puppet PC1 (4.6.x)

What distro and Puppet version are you using?

**Comment by FlorinTar** [comment]
Puppet 4.10.4
and CentOS 6.9

**Comment by FlorinTar** [comment]
It works with Splunk 6.5.4 without a problem.

**Comment by jorritfolmer** [comment]
I'm also not able to reproduce it with the newest Puppet PC1 4.10.4 with Augeas 1.4.0, similar to your env (and Splunk 6.6.1).

Can you post splunk-lauch.conf file? Perhaps there is something in there that borks augeas?

This is the debug output I'm getting for a succesful run:

```
Debug: Augeas[/opt/splunk/etc/splunk-launch.conf splunk_os_user](provider=augeas): Opening augeas with root /, lens path , flags 64
Debug: Augeas[/opt/splunk/etc/splunk-launch.conf splunk_os_user](provider=augeas): Augeas version 1.4.0 is installed
Debug: Augeas[/opt/splunk/etc/splunk-launch.conf splunk_os_user](provider=augeas): Will attempt to save and only run if files changed
Debug: Augeas[/opt/splunk/etc/splunk-launch.conf splunk_os_user](provider=augeas): sending command 'set' with params ["/files/opt/splunk/etc/splunk-launch.conf/SPLUNK_OS_USER", "splunk"]
Debug: Executing: 'diff -u /opt/splunk/etc/splunk-launch.conf /opt/splunk/etc/splunk-launch.conf.augnew'
Notice: Augeas[/opt/splunk/etc/splunk-launch.conf splunk_os_user](provider=augeas): 
--- /opt/splunk/etc/splunk-launch.conf	2017-06-21 19:11:09.929199623 +0200
+++ /opt/splunk/etc/splunk-launch.conf.augnew	2017-06-21 19:11:21.097437074 +0200
@@ -23,3 +23,4 @@
 # (This setting can be specified as username or as UID.)
 #
 # SPLUNK_OS_USER
+SPLUNK_OS_USER=splunk

Debug: Augeas[/opt/splunk/etc/splunk-launch.conf splunk_os_user](provider=augeas): Files changed, should execute
Debug: Augeas[/opt/splunk/etc/splunk-launch.conf splunk_os_user](provider=augeas): sending command 'set' with params ["/files/opt/splunk/etc/splunk-launch.conf/SPLUNK_OS_USER", "splunk"]
Debug: Augeas[/opt/splunk/etc/splunk-launch.conf splunk_os_user](provider=augeas): Closed the augeas connection
Notice: /Stage[main]/Splunk::Splunk_launch/Augeas[/opt/splunk/etc/splunk-launch.conf splunk_os_user]/returns: executed successfully
Debug: /Stage[main]/Splunk::Splunk_launch/Augeas[/opt/splunk/etc/splunk-launch.conf splunk_os_user]: The container Class[Splunk::Splunk_launch] will propagate my refresh event
Debug: Augeas[/opt/splunk/etc/splunk-launch.conf splunk_bindip](provider=augeas): Opening augeas with root /, lens path , flags 64
Debug: Augeas[/opt/splunk/etc/splunk-launch.conf splunk_bindip](provider=augeas): Augeas version 1.4.0 is installed
Debug: Augeas[/opt/splunk/etc/splunk-launch.conf splunk_bindip](provider=augeas): Will attempt to save and only run if files changed
Debug: Augeas[/opt/splunk/etc/splunk-launch.conf splunk_bindip](provider=augeas): sending command 'rm' with params ["/files/opt/splunk/etc/splunk-launch.conf/SPLUNK_BINDIP"]
Debug: Augeas[/opt/splunk/etc/splunk-launch.conf splunk_bindip](provider=augeas): Skipping because no files were changed
Debug: Augeas[/opt/splunk/etc/splunk-launch.conf splunk_bindip](provider=augeas): Closed the augeas connection
Debug: Class[Splunk::Splunk_launch]: The container Stage[main] will propagate my refresh event

```

**Comment by FlorinTar** [comment]
I'm using vagrant to deploy the environment, there is no splunk-lauch.conf at the time of error.

Here's my vagrant file content and some more details:

Vagrant.configure(2) do |config|
  #Hostmanager plugin enabled to update host files
  #   vagrant plugin install vagrant plugin install
  config.hostmanager.enabled = true

  config.vm.define "splunk1" do |splunk1|
    splunk1.vm.box = "puppetlabs/centos-6.6-64-nocm"
    splunk1.vm.hostname = "splunk1.local"
    splunk1.vm.provider "virtualbox" do |vb|
      vb.memory = "3072"
    end
    splunk1.vm.network "private_network", ip: '10.200.200.20', :name => 'vboxnet5', :adapter => 2

    splunk1.vm.provision "shell", :inline => <<-SHELL
      service iptables stop
      yum update -y
      rpm -ivh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-6.noarch.rpm
      yum install -y puppet tree
      /opt/puppetlabs/bin/puppet apply \
      --hiera_config /vagrant/files/hiera/hiera.yaml \
      --modulepath /vagrant/files/modules \
      -e "include role::opsplk"

$ tree -I 'splunk|stdlib' files/
files/
├── hiera
│   ├── common.yaml
│   └── hiera.yaml
├── manifests
│   └── site.pp
├── modules
│   ├── manifests
│   ├── profile
│   │   └── manifests
│   └── role
│       └── manifests
│           ├── opsplk.pp
│           └── opspuf.pp
└── splunk
    ├── splunk-6.6.1-aeae3fe0c5af-linux-2.6-x86_64.rpm
    └── splunkforwarder-6.6.1-aeae3fe0c5af-linux-2.6-x86_64.rpm



$ cat files/modules/role/manifests/opsplk.pp
class role::opsplk {
  notify { 'apply opsplk role': }

  yumrepo { "splunk":
  baseurl => "http://puppet.local/splunk",
  descr => "Splunk repo off puppet server",
  enabled => 1,
  gpgcheck => 0
  }
  class { 'splunk':
    httpport           => 8000,
    kvstoreport        => 8191,
    inputport          => 9997,
    reuse_puppet_certs => false,
    sslcertpath        => 'server.pem',
    sslrootcapath      => 'cacert.pem',
  }
}
$ cat files/manifests/site.pp
node default {
  # This is where you can declare classes for all nodes.
  # Example:
  #   class { 'my_class': }
  notify { "This is ${::fqdn}, running the ${::operatingsystem} operating system": }

}



The repository sits onto http://puppet.local/splunk

**Comment by FlorinTar** [comment]
It's catching all sorts of formatting, see it here raw: https://pastebin.com/WuY5PFXG

**Comment by jorritfolmer** [comment]
If you don't have a splunk-launch.conf file, something went wrong with the rpm install.
The result of a Splunk install from rpm should be an /opt/splunk filled with 14620 files, of which  /opt/splunk/etc/splunk-launch.conf is one.

In your Puppet manifest, perhaps you should try to make the splunk class depend on the yumrepo with `->`,  or a `require => Yumrepo["splunk"]` in the splunk class.
This makes sure the repo gets created first, so you're guaranteed to have a repo when the splunk class tries to install the rpm from the repo. It may work without these dependencies, but it isn't guaranteed.

**Comment by FlorinTar** [comment]
Using required or even before Service['splunk'] didn't help, I get exact same error.
It looks to me that somehow it's skipping the requirement of having splunk installed.

I've tried required Package["splunk"] and I got a conflict with /splunk/manifests/installed.pp:9

**Comment by FlorinTar** [comment]
I've also tried the following steps:
- Create repo then use then use puppet class to configure splunk --> Fail
- install splunk manually with yum then use then use puppet class to configure splunk --> Success

**Comment by FlorinTar** [comment]
Hey, I've figured it out.
Run puppet with --noop and you will get the error, however if you leave it to run without --noop it will work just fine.

**Comment by jorritfolmer** [comment]
Thanks, good to hear!
