### ISSUE TITLE
Future: make use of "indexer discovery"

### ISSUE THREAD

**Issue by FlorinTar** [jorritfolmer/puppet-splunk#14]
Hi,
I love your module, it's great easy and future reach.

I'd like to recommend switching from "direct peer node" to "indexer discovery", it will greatly reduce maintenance both code and UF node, see link below. 

http://docs.splunk.com/Documentation/Splunk/6.6.2/Indexer/indexerdiscovery#Configure_indexer_discovery_with_SSL

Also, it would be useful if your instructions would contain a heavy forwarder example.

Thanks for the great module and tanks for sharing!

**Comment by jorritfolmer** [comment]
Thanks for the suggestions!
I'll look into them later this month.

**Comment by jorritfolmer** [comment]
I've just added indexer discovery in v3.4.0

**Comment by FlorinTar** [comment]
That's great, thank you, I'll test it out tomorrow.

**Comment by FlorinTar** [comment]
Works perfectly. Thank you!
