### ISSUE TITLE
Universal forwarder is not using puppet signed ceritificate

### ISSUE THREAD

**Issue by FlorinTar** [jorritfolmer/puppet-splunk#15]
Hi 
I've noticed the below error in a UF:

07-06-2017 12:53:03.818 +0000 WARN  X509Verify - X509 certificate (O=SplunkUser,CN=SplunkServerDefaultCert) should not be used, as it is issued by Splunk's own default Certificate Authority (CA). This puts your Splunk instance at very high-risk of the MITM attack. Either commercial-CA-signed or self-CA-signed certificates must be used; see: <http://docs.splunk.com/Documentation/Splunk/latest/Security/Howtoself-signcertificates>

Is this a bug or it's not implemented by default ?
This is my code for UF:

class { 'splunk':
    type         => 'uf',
    ds           => $master,
    pass4symmkey => $pass4symmkey,
    tcpout       => [ $index1, $index2, $index3 ],
    admin        => {
      hash  => $admin_hash,
      fn    => 'Forwarder Administrator',
      email => $email,
    },
    service      => {
      ensure => running,
      enable => true,
    }
  }

**Comment by jorritfolmer** [comment]
From looking at Wireshark I see this:
- no client certificate is presented by the UF, neither issued by Splunk nor by Puppet
- the Puppet issued certificate is presented by the indexer
- a secure TLS channel is established

It appears this warning doesn't apply to the connection between UF and indexer.

**Comment by jorritfolmer** [comment]
Further digging:

- a client certificate is only presented at the request of the server, configured with `requireClientCert = true` in inputs.conf.
- `requireClientCert` defaults to off

**Comment by FlorinTar** [comment]
Thank you,
It's probably better to enable `requireClientCert = true` and use the puppet signed certificate to improve security, however, this looks like an enhancement rather than an issue.

I was worried that it's using the self-signed certificate for authentication.
I'm not closing the issue in case you would like to add anything else.

Thank you very much for your turnaround

**Comment by jorritfolmer** [comment]
I've just released v3.3.0 that adds `requireclientcert` as a parameter.
You have to explicitly enable it for now. I may enable it by default when we get to version v4.0
