### ISSUE TITLE
Add support for package_source also for Linux

### ISSUE THREAD

**Issue by mirogta** [jorritfolmer/puppet-splunk#17]
Currently package_source parameter works only for Windows.

When I've tried to install splunk on RHEL 3.10.0-514.26.2.el7.x86_64 it has produced this error:

> Error: Could not update: Execution of '/bin/yum -d 0 -e 0 -y install splunk' returned 1: Error: Nothing to do
> Error: /Stage[main]/Splunk::Installed/Package[splunk]/ensure: change from purged to present failed: Could not update: Execution of '/bin/yum -d 0 -e 0 -y install splunk' returned 1: Error: Nothing to do
> Notice: /Stage[main]/Splunk::Installed/Exec[splunk enable boot-start etcetera]: Dependency Package[splunk] has failures: true

I've got the same error when I've provided splunk version 
```
  class { 'splunk':
    version     => '6.6.2-4b804538c686',
    httpport    => 8000,
    kvstoreport => 8191,
    inputport   => 9997,
  }
```

> Error: Could not update: Execution of '/bin/yum -d 0 -e 0 -y install splunk' returned 1: Error: Nothing to do
> Error: /Stage[main]/Splunk::Installed/Package[splunk]/ensure: change from purged to 6.6.2 failed: Could not update: Execution of '/bin/yum -d 0 -e 0 -y install splunk-6.6.2' returned 1: Error: Nothing to do
> Notice: /Stage[main]/Splunk::Installed/Exec[splunk enable boot-start etcetera]: Dependency Package[splunk] has failures: true

I've only managed to install splunk from the command line by providing a full URL:

```
yum install install https://download.splunk.com/products/splunk/releases/6.6.2/linux/splunk-6.6.2-4b804538c686-linux-2.6-x86_64.rpm
```

Is it possible to add support for package_source also for Linux, or add a condition not to fail the puppet run in case I have installed splunk manually?

```
  package { 'splunk-yum':
   provider => 'yum',
   name     => 'https://download.splunk.com/products/splunk/releases/6.6.2/linux/splunk-6.6.2-4b804538c686-linux-2.6-x86_64.rpm',
   ensure   => present,
  
  class { 'splunk':
    skip_installation     => true,
    httpport    => 8000,
    kvstoreport => 8191,
    inputport   => 9997,
  }
```

**Comment by jorritfolmer** [comment]
Done! See most recent commit!

**Comment by mirogta** [comment]
Perfect! Works like a charm.

Thank you for such a quick turnaround.
