### ISSUE TITLE
Splunk service restart loop after updating from puppet 3 to 4

### ISSUE THREAD

**Issue by stmyers** [jorritfolmer/puppet-splunk#19]
This started happening on all our forwarders after updating recently....I can see what's happening but am having a hard to figuring out how to stop it.  The value is getting changed to the default, uf gets restarted and the value gets encrypted, puppet see that it doesn't match and resets it back to default, service is restarted and value gets encrypted again...rinse and repeat. I must be missing something obvious....
`Notice: /Stage[main]/Splunk::Server::General/File[/opt/splunkforwarder/etc/apps/puppet_common_pass4symmkey_base/local/server.conf]/content: content changed '{md5}e03e7073e0cf85c462adac7e2d997ba2' to '{md5}ed056538b79d38db26e26824097b5888'
Notice: /Stage[main]/Splunk::Service/Service[splunk]: Triggered 'refresh' from 1 events`

**Comment by jorritfolmer** [comment]
I'll look into it, what does your UF config look like?

**Comment by jorritfolmer** [comment]
I'm unable to reproduce this for a UF config with Puppet 4.10.4 (from Puppet Collections 1) on RHEL7.
After a Puppet run it's changed back to the default, but Splunk isn't notified to restart. I've tried both with service and without service parameter.

I've used this hieradata YAML for the node config:

```
---
classes:
  - splunk

splunk::type:             uf
splunk::tcpout:           host11.testlab.local:9997
splunk::ds:               host11.testlab.local:8089
splunk::sslcompatibility: intermediate
splunk::version:          6.6.1-aeae3fe0c5af
splunk::service:
  ensure:                 running
  enable:                 true
```

**Comment by stmyers** [comment]
Disregard....the pass4symmkey was a red herring....it was something else unrelated that was triggering the service refresh
