### ISSUE TITLE
Managing inputs.conf with puppet?

### ISSUE THREAD

**Issue by timidri** [jorritfolmer/puppet-splunk#2]
Hi Jorrit,

Thanks for the module - I am trying to use it to deploy universal forwarders. We don't yet have a deployment server available, so we need to manage inputs.conf with puppet. The only approach I see working as the module is now is using augeas but that quickly can get quite messy. Is it possible to allow management of inputs.conf in some other way, for instance using a custom content snippet?

**Comment by jorritfolmer** [comment]
You may want to take a look at [the Splunk module from Harvard](https://github.com/huit/puppet-splunk). They have a splunk::inputs class available which probably suits your use-case.

**Comment by timidri** [comment]
@jorritfolmer thanks, that's what we ended up doing.
