### ISSUE TITLE
Just upgraded to Splunk 7 - issues with certs

### ISSUE THREAD

**Issue by stmyers** [jorritfolmer/puppet-splunk#23]
I haven't had time to dig into this but after upgrading to 7, I'm having issues with 
`ERROR TcpOutputFd - Read error. Connection reset by peer`
on all the forwarders and 
`ERROR TcpInputProc - Error encountered for connection from src=<ip>:39570. error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol`
on all the indexers.

Right before upgrading, I implemented indexer discovery, but besides that nothing in the module changed between version 6 and upgrading to 7.  Did I miss something?

**Comment by jorritfolmer** [comment]
Two weeks I deployed a Splunk 7.0.1 cluster with version 3.5.0 of this module. No issues there. However, I have never explicitly tested an upgrade, but would expect it to work.

What does this say from a UF to one of your indexers?
```
openssl s_client -connect your_indexer:9997
```

Any errors right after starting a UF?

**Comment by stmyers** [comment]
Now that I've had some more time to look at it, it appears that it's related to the indexer discovery that I've enabled.  The src forwarders in the error events on the indexers (src=<ip> in my example) are all from the opposite site of the indexer.  

After running an s_client from a random forwarder, to the same-site idx and cross-site idx I'm not seeing anything that jumps out at me.  Can I email you sample outputs? I don't want to post here.

**Comment by jorritfolmer** [comment]
From your openssl output It looks like there are 2 Puppet Masters, one for each site. This means that a UF on one site cannot verify the cert from the indexer on another because they dont share a common root CA. If you also enabled client certificate verification on the indexer then the indexers will also fail to verify the UFs.

You could try to add both site CA certificates to the ca.crt manually.

**Comment by stmyers** [comment]
Thanks I should have realized that.

**Comment by jorritfolmer** [comment]
Reading up on multi-site Puppet masters, it appears you can separate the CA function from the manifest compilation function. So you'll have a Puppet master for each site that does the manifest compilation and such, like you have now. And additionally a (single) Puppet CA that's only used for the puppet cert sign stuff.
