### ISSUE TITLE
Indexer Discovery - Cluster Master doesn't have cm specified which causes issues with forwarding from CM to indexers

### ISSUE THREAD

**Issue by stmyers** [jorritfolmer/puppet-splunk#24]
I recently enabled indexer discovery and came across this problem.

My CM doesn't have cm defined under clustering so this is what the outputs.conf on the CM looks like:
```
~/etc/apps $ cat puppet_common_ssl_outputs/local/outputs.conf
[tcpout]
defaultGroup = cluster

[tcpout:cluster]
indexerDiscovery = cluster
sslCertPath = /opt/splunk/etc/auth/certs/s2s.pem
sslRootCAPath = /opt/splunk/etc/auth/certs/ca.crt
useACK = false

[indexer_discovery:cluster]
pass4SymmKey = <redacted>
master_uri = https://
```

Notice the empty `master_uri`.

My CM wasn't forwarding events (or storing them locally because that was disabled), until I added this to system\local\outputs.conf
```
[indexer_discovery:cluster]
master_uri = https://clustermasterurl:8089
```

Then logs started flowing.  I don't think this is clarified in the code, but it's definitely not accounted for in the indexer discovery example.  Should I have assumed I need to set cm under clustering for the Cluster Master, since it is also a forwarder after all?

**Comment by jorritfolmer** [comment]
You shouldn't have to set `cm` for the Cluster Master. On line 23 of manifests/outputs.pp it sets a cm variable to itself ($::fqdn:8089) if cm is empty. Further in templates/puppet_common_ssl_outputs/local/outputs.conf it uses this variable if indexer_discovery is set for tcpout. I'm not sure why this isn't working for you.

I'm using the following for the hiera YAML definition of the cluster master. It results in a working indexer_discovery with cm set:

```
splunk::httpport:           8000
splunk::reuse_puppet_certs: false
splunk::sslcertpath:        server.pem
splunk::sslrootcapath:      cacert.pem
splunk::sslpassword:        <redacted>
splunk::tcpout:             indexer_discovery
splunk::use_ack:            true
splunk::clustering:
  mode:                     master
  replication_factor:       2
  search_factor:            2
  indexer_discovery:        true
  pass4symmkey:             <redacted>
splunk::admin:
  hash:                     <redacted>
  fn:                       CM Administrator
  email:                    <redacted>
```

resulting outputs.conf:

```
[tcpout]
defaultGroup = cluster

[tcpout:cluster]
indexerDiscovery = cluster
sslCertPath = /opt/splunk/etc/auth/server.pem
sslRootCAPath = /opt/splunk/etc/auth/cacert.pem
sslPassword = <redacted>
useACK = true

[indexer_discovery:cluster]
pass4SymmKey = <redacted>
master_uri = https://host03.testlab.local:8089
```

**Comment by stmyers** [comment]
Ahh...for some reason I don't remember, I have defined non-UF types in hiera.
```
...
# Cluster Master
splunk::type: cm
...
```

I really don't know why I did this....reviewing my code, I don't use it anywhere.....I think I was just labeling things my my own sake.
