### ISSUE TITLE
Splunk::Installed class has following error: Error: Could not find command '/opt/splunkforwarder/bin/splunk' Error: /Stage[main]/Splunk::Installed/Exec[splunk initial run]/returns: change from 'notrun' to ['0'] failed: Could not find command '/opt/splunkforwarder/bin/splunk'

### ISSUE THREAD

**Issue by dkangel37** [jorritfolmer/puppet-splunk#25]
Trying to install the Splunk UF using the Splunk::Installed class and I am running into the following error:

Error: Could not find command '/opt/splunkforwarder/bin/splunk'
Error: /Stage[main]/Splunk::Installed/Exec[splunk initial run]/returns: change from 'notrun' to ['0'] failed: Could not find command '/opt/splunkforwarder/bin/splunk'

can you assist? I am using puppet enterprise.

**Comment by jorritfolmer** [comment]
Thanks for the bug report!
It appears the first time run may sometimes happen before the rpm is installed.
I've fixed this in v3.9.1.
Can you verify?

**Comment by dkangel37** [comment]
OK upgraded and reran everything. Now i'm getting the following error:

Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Cannot alias File[/etc/apps/puppet_common_deploymentclient_base/] to ["/etc/apps/puppet_common_deploymentclient_base"] at /etc/puppetlabs/code/environments/production/modules/splunk/manifests/deploymentclient.pp:29; resource ["File", "/etc/apps/puppet_common_deploymentclient_base"] already declared at /etc/puppetlabs/code/environments/production/modules/splunk/manifests/deploymentclient.pp:29 at /etc/puppetlabs/code/environments/production/modules/splunk/manifests/deploymentclient.pp:29:5 on node XXX

**Comment by jorritfolmer** [comment]
Looks like the $splunk_home variable is empty. E.g. File[/etc/apps/puppet_common_deploymentclient_base/] should be
File[/opt/splunkforwarder/etc/apps/puppet_common_deploymentclient_base/]

Can you share your Puppet manifest of hieradata?

**Comment by dkangel37** [comment]
Well i utilized the ds options under the main splunk class and the ds piece installed without issue. I don't plan on using the splunk::deploymentclient class now. 

What part of the Puppet manifest do you need to troubleshoot? Not using Hiera. We're using Puppet Enterprise and the console to setup the classes.

**Comment by jorritfolmer** [comment]
I need to the node part from site.pp where you use the splunk class.

BTW: the Splunk subclasses aren't meant to be used individually. That probably explains why you're getting weird results like missing $splunk_home stuff above. Everything should be done from the main splunk class.

**Comment by dkangel37** [comment]
Our site.pp does not include a node option. The below is all that's in the site.pp. Also i adjusted to use just the splunk class to run the install..it's giving me an error on the Splunk::installed piece about missing the user even those i've included the user within the main splunk class. To make it run had to add the splunk::installed class and put the user option there. Then it fails because it can't enable splunk, This is due to the /opt/splunkforwarder/var  directory being owned by root for some reason. 


yumrepo {"splunk":
 baseurl =>"http://site/repo/splunk",
 descr =>"Splunk_Repo",
 enabled => 1,
 gpgcheck => 0
