### ISSUE TITLE
server.conf template spacing causes changes after Splunk restart

### ISSUE THREAD

**Issue by vidkun** [jorritfolmer/puppet-splunk#28]
The spacing around the `=` for `enableSplunkdSSL` in `puppet-splunk/templates/puppet_common_ssl_base/local/server.conf` is causing a change/update to the file on every Puppet run following a restart of Splunk.

Restarting Splunk causes Splunk to cleanup the server.conf with spacing around the `=` for each setting. The next Puppet run detects it as a change and reverts it back to missing the spacing.

If you've implemented an exec to restart Splunk when this conf file changes, it will force a Splunk restart on every Puppet run. Thus, causing an endless loop of Splunk restarts on every Puppet run.

**Comment by jorritfolmer** [comment]
Thanks!
