### ISSUE TITLE
Cannot add searchpeers parameter in Puppet Enterprise

### ISSUE THREAD

**Issue by dkangel37** [jorritfolmer/puppet-splunk#32]
I am attempting to set up a Search Head but i cam getting the following error when i update the splunk module within Puppet Enterprise classification. I am using two peers but i have also tested it with just one..with the same error. Can you assist?

2018-04-0415:34 Z | err | Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Operator '[]' is not applicable to an Undef Value. at /etc/puppetlabs/code/environments/production/modules/splunk/manifests/addsearchpeers.pp:11:18 at /etc/puppetlabs/code/environments/production/modules/splunk/manifests/init.pp:189 on node Source:
-- | -- | --

**Comment by jorritfolmer** [comment]
You have to add the plaintext admin password to the auth parameter, because we actually run a splunk command in the background that needs to authenticate to the search peer with the admin password.
That isn't exactly clear from the error message, nor from the documentation.

So I've added better error handling and documentation a minute ago.
Thanks for submitting the issue btw!

**Comment by dkangel37** [comment]
So I added the admin parameter within the Puppet Enterprise GUI and got the same error. I've also confirmed that the admin password has been updated on all servers.
**Current Splunk Class Configs:**
lm  =  "x.x.x.x:8089" 
ds = "x.x.x.x:8089"
admin = {pass="changemeagain"}
tcpout = ["x.x.x.22:9997","x.x.x.32:9997"] 
searchpeers = ["x.x.x.22:8089","x.x.x.32:8089"] 
kvstoreport  =  8190 
httpport = 8000

Thoughts?

**Comment by jorritfolmer** [comment]
Thanks for finding these issues!
The error is because of the implicit assumption that all the fields under admin (hash, fn, email) are filled, which isn't the case here.
I've fixed them in the most recent commit and expanded the test cases for these conditions.

**Comment by dkangel37** [comment]
So I added the hash, fn and e-mail to the GUI, unfortunately got the same error. It still thinks it's a String and actually the PE GUI says it converted it to a string as well, seems it can't parse it as a JSON. See the information block from PE below:

> Structured parameters
> Class parameters can be structured as JSON. If we can't parse your parameter as JSON we'll send it to the classifier service as a string.
> 

admin ={hash='54FECFA3E1DD12C6F35E4F0825006391C410C593E6E7B7F0A4C7E04F91316435F710DAA3FA95CF0F61186D55A7C72DF44EDB1D361E8239D33D2E9E9DDF320D97',fn='SplunkSH1',email='anything@example.com'}"

**Comment by jorritfolmer** [comment]
JSON uses a colon (:) to assign values to keys instead of an equal sign (=).
Did you try something like this below?

{'hash': '54FECFA3E1Detcetc', 'fn': 'SplunkSH1', 'email': 'anything@example.com', 'pass': 'plaintextpassword'}

**Comment by dkangel37** [comment]
Yes I have.  I get the same error unfortunately

**Comment by jorritfolmer** [comment]
Ok I'll have a look, might take a while because I killed my PE test instance

**Comment by dkangel37** [comment]
Hi There, any luck with testing this issue?

Thanks.

**Comment by jorritfolmer** [comment]
I got back to testing this issue again.
Short answer: you should specify the admin parameter in JSON notation. This means double quotes, and colons between curly braces.

| Status | Statement | Reason
|------|-----|-----
| **Works** | `{"pass": "changemeagain"}` | Valid JSON
| Doesn't work | `{'pass': 'changemeagain'}` | Invalid JSON
| Doesn't work | `{pass: "changemeagain"}` | Invalid JSON
| Doesn't work | `{pass= "changemeagain"}` | Invalid JSON
| Doesn't work | `{"hash": "$6$MR9IJetc"}` | Valid JSON but $ causes variable interpolation
| Doesn't work | `{"hash": "\$6\$MR9IJetc"}` | Valid JSON but escaped $ causes PE webgui to interfere|

So for your purposes the `pass` statement for adding searchpeers should work. However if you want to set the admin hash through the PE web gui, this won't work. This looks like a bug in the web gui methinks.

More info over at https://puppet.com/docs/pe/2017.3/managing_nodes/grouping_and_classifying_nodes.html#set-node-group-variables

**Comment by jorritfolmer** [comment]
I've updated the docs with this info
