### ISSUE TITLE
reuse_puppet_certs does not use puppet certs

### ISSUE THREAD

**Issue by vidkun** [jorritfolmer/puppet-splunk#35]
Using the latest 3.11.0 release and leaving `reuse_puppet_certs` at default is resulting in Splunk using the default Splunk-provided cert instead of using the certs from Puppet CA. At least Splunk web is using that default Splunk cert. Is this expected behavior or am I overlooking something?

Steps to reproduce:
* provision new RHEL host and hook to Puppet
* use Puppet to install Splunk 7.0.3 with `reuse_puppet_certs` left at default value

Expected Behavior: Splunk web presents a certificate from our internal Puppet CA.

Actual Behavior: It presents the default Splunk certificate from SplunkCommonCA.

**Comment by jorritfolmer** [comment]
Agreed, the web cert should be the one signed by the Puppet CA.
Additionally, for search head clusters we may need some extra parameters to override the web cert to present a single cert on all shc member nodes.

**Comment by vidkun** [comment]
Any ideas why it is not currently using the Puppet CA cert then?

RE: shc certs - I would think best practice would be to hit the cluster via a load balancer with sticky sessions. In that case, just put the main cert on the LB to present to the client and then each of the shc members could still use their own Puppet CA certs (or whichever cert). This would alleviate the need for all shc member nodes to have the same cert.

On the other hand, could we not just set `reuse_puppet_certs` to false and use the `ssl*` parameters to configure all the shc members to reuse the same cert?

**Comment by vidkun** [comment]
I don't see where `privKeyPath` and `serverCert` are being set in `web.conf` in `puppet_common_ssl_web_base` or anywhere else.

Also, looks like [s2s.pp](https://github.com/jorritfolmer/puppet-splunk/blob/82efb87f779eefa9c146f8592cd5fc2af42a8597/manifests/certs/s2s.pp#L122) has a creates looking for hard-coded `s2s.pem` when the command actually creates the file named after the value of `sslcertpath`.

I'm not sure if that's the cause of the issue and can't test it at the moment.

**Comment by jorritfolmer** [comment]
Yes it appears I never implemented it.

What about:
- introduce a new parameter `reuse_puppet_certs_for_web`, which will default to false to keep the current behaviour for backwards compatibility reasons
- when set to true, we'll point the privKeyPath and serverCert to the Puppet key and cert, and make sure these files are available

?

**Comment by vidkun** [comment]
I think that would work. A cleaner solution would likely require a more significant rewrite and potentially involve some breaking changes.

The above should at least implement the functionality for those needing it with minimal impact to others.
