### ISSUE TITLE
Admin Pass Param

### ISSUE THREAD

**Issue by hodgsonsam** [jorritfolmer/puppet-splunk#36]
Hi,

Im having some difficulty in declaring the admin param.  Im using Puppet Enterprise 2018 and hiera.  I initially tried defining in hiera with the following:

`---
classes:
  - apt-test
  - splunk

splunk::httpport:         8000
splunk::kvstoreport:      8191
splunk::inputport:        9997
splunk::package_source:   "splunk"
splunk::admin:  {"pass": "changemeagain"}`

Then tried adding in the Puppet console under the node classification.  

Class: Splunk
Parameter: Admin
Value: {"pass": "changemeagain"}

Neither seem to work, I get an error saying no users exist when I try to login for the first time.I cant see any errors or warnings in the puppet output on the agent.

Any assistance on this would be greatly appreciated.

Cheers

**Comment by FlorinTar** [comment]
I think you need something like this 
`  class { 'splunk':
    admin        => {
      hash  => $admin_hash,
      fn    => 'Cluster Master Administrator',
      email => $opspk_email,
    }`

where $admin_hash is the password generated in the following maner
# To produce a hash:
# grub-crypt --sha-512 (RHEL/CENTOS)
# OR
# python -c 'import crypt,getpass; print(crypt.crypt(getpass.getpass(), crypt.mksalt(crypt.METHOD_SHA512)))'

**Comment by hodgsonsam** [comment]
Many thanks for the response FlorinTar, I have found a workaround however ideally I would have liked to define this in hiera, which is probably possible but im quite new to it.

**Comment by jorritfolmer** [comment]
In Hiera it should look something like this:

```
classes:
  - apt-test
  - splunk

splunk::httpport:           8000
splunk::kvstoreport:        8191
splunk::inputport:          9997
splunk::package_source:     "splunk"
splunk::admin:
  pass:                     changemeagain
  hash:                     '$6$MR9IJFF7RBnVA.k1$etcetc'
```

**Comment by hodgsonsam** [comment]
Awesome cheers Jorrit
