### ISSUE TITLE
Convert module to utilize PDK

### ISSUE THREAD

**Issue by TraGicCode** [jorritfolmer/puppet-splunk#39]
In order to get a PDK badge and also keep up-to-date with the latest development standards for puppet modules it would be best to convert this module into a pdk compatible one.  If you have no problems with this i can start on the work for this.

**Comment by jorritfolmer** [comment]
I haven’t read up on PDK yet, but from a distance this looks like a good idea.
Does it affect backward compatibility or add new dependencies?

**Comment by TraGicCode** [comment]
> Does it affect backward compatibility

Nope

> add new dependencies

No it does not


If you want i can convert it to the pdk and then get your feedback about what needs to be changed/updated.  Generally, if you have certain customizations in your rake file, travis-ci file, or gemfile we need to manually call those out.  let me know what you think.

**Comment by TraGicCode** [comment]
Closing since i've moved on to other things
