### ISSUE TITLE
Puppet cert locations on RHEL

### ISSUE THREAD

**Issue by TheChuckMo** [jorritfolmer/puppet-splunk#4]
I have a fairly minor issue. I'm going to clone to make some quick updates, but in short: The Red Hat provided puppet packages place the puppet certs under /var/lib/puppet/ssl instead of /etc/puppet/ssl. 

My plan is to clone and update the cert location in master/manifests/certs/s2s.pp based on the $osfamily fact. I'd also be open, if desired, to adding a cert location parameter in params.pp to make changeable if the certs get moved again.  

-Chuck

**Comment by jorritfolmer** [comment]
Yes good catch! Thanks!

**Comment by jorritfolmer** [comment]
Closed with 970778d
