### ISSUE TITLE
Add Beaker acceptance tests that use docker in travis-ci

### ISSUE THREAD

**Issue by TraGicCode** [jorritfolmer/puppet-splunk#40]
I would like to add some basic beaker acceptance tests for this module that will spinup splunk in docker containers and make assertions to catch bugs/issues/regressions with this module.  Let me know how this sounds and i can start some work on this and get your input.

**Comment by jorritfolmer** [comment]
Sounds excellent!

**Comment by TraGicCode** [comment]
Wow....so first thing i ran into is something i didn't expect to run into.  This repository contains a folder in templates called aux.  When you try to clone this repo on a windows system it fails because windows prevents you from creating folders that match system devices. 

https://social.technet.microsoft.com/Forums/ie/en-US/d1cf7394-a39b-46bf-823d-46f33b2f78d0/unable-to-create-folder-named-quotauxquot-anywhere-in-the-disk?forum=w7itprogeneral

https://stackoverflow.com/questions/36225708/cannot-create-a-directory-named-aux-or-starting-by-aux-on-windows-8-1

Could we rename this folder in the github repository to "log" or something else of your choosing instead?

Thanks!

**Comment by TraGicCode** [comment]
Closing since i've moved on to other things
