### ISSUE TITLE
Option to disable management of Splunk service

### ISSUE THREAD

**Issue by Rathios** [jorritfolmer/puppet-splunk#46]
We want to manage the Splunk Forwarder service ourselves using a systemd service/unit file (Splunk does not provide one with the rpm as of 7.0.1), but there is currently no way to do this because the module doesn't allow use of a systemd service as long as the status, start and stop parameters override it. The service resource in the module can't be disabled either.

```
status => "${splunk_home}/bin/splunk status",
start  => "${splunk_home}/bin/splunk start",
stop   => "${splunk_home}/bin/splunk stop",
```

A simple $manage_service variable would fix this.

**Comment by jorritfolmer** [comment]
Can you verify if the patch below works is intended?
It allows you to disable any interference with service management by the Splunk module.

```
service      => {
      ensure     => undef,
      enable     => undef,
    },
```

```
--- a/manifests/service.pp
+++ b/manifests/service.pp
@@ -26,20 +26,22 @@ class splunk::service (
       }
     }
     default: {
-      if $service[ensure] == undef {
-        service { 'splunk':
-          enable => $service[enable],
-          status => "${splunk_home}/bin/splunk status",
-          start  => "${splunk_home}/bin/splunk start",
-          stop   => "${splunk_home}/bin/splunk stop",
-        }
-      } else {
-        service { 'splunk':
-          ensure => $service[ensure],
-          enable => $service[enable],
-          status => "${splunk_home}/bin/splunk status",
-          start  => "${splunk_home}/bin/splunk start",
-          stop   => "${splunk_home}/bin/splunk stop",
+      if $service[enable] == undef {
+        if $service[ensure] == undef {
+          service { 'splunk':
+            enable => $service[enable],
+            status => "${splunk_home}/bin/splunk status",
+            start  => "${splunk_home}/bin/splunk start",
+            stop   => "${splunk_home}/bin/splunk stop",
+          }
+        } else {
+          service { 'splunk':
+            ensure => $service[ensure],
+            enable => $service[enable],
+            status => "${splunk_home}/bin/splunk status",
+            start  => "${splunk_home}/bin/splunk start",
+            stop   => "${splunk_home}/bin/splunk stop",
+          }
         }
       }
     }
```

**Comment by jorritfolmer** [comment]
Ok forget the (deleted) patch.
Much easier to create a new variable indeed.

**Comment by jorritfolmer** [comment]
Can you check if 106c50d0e5bebc70bcc9eb8b8bcc88702dd6b051 does what you need?

**Comment by Rathios** [comment]
Thanks for a fast response :)

Yep, that does the trick. There's just one thing missing. If managed is set to true it will still not manage it. Something like this should do the trick.

`if $service[managed] == undef or $service[managed] == true {`

You could also move the conditional check so it's the outermost condition, so it will do the same for Windows as well.

**Comment by jorritfolmer** [comment]
Thanks for the suggestion, will fix it!

**Comment by jorritfolmer** [comment]
Done

**Comment by Rathios** [comment]
Works as expected on Linux. Solved :) thanks!

We don't have any Windows machines with Puppet yet so I haven't been able to test it there. But it should work.
